### PR TITLE
Fix service external ip not cleared

### LINKED ISSUE #11: The loadbalancer external ip is not cleared when the tunnel is removed
If I manually remove the tunnel object associated to a loadbalancer, the garbage collector does not clear the external ip of the service. This make the loadbalancer service state inconsistent.

I already have a working fix so I could open a PR with it.

## Expected Behaviour
I would expect the node-exit ip to be removed from the externalips on the loadbalancer service.

## Steps to Reproduce 
1. Create a new loadblancer service
```	
kubectl run nginx-1 --image=nginx --port=80 --restart=Always
kubectl expose deployment nginx-1 --port=80 --type=LoadBalancer
```

This will make the inlets operator to create a new tunnel and update the service with the exit node ip.

2. Annotate de loadbalaner with `dev.inlets.manage=false`

This is where I think this is an edge case. This is because I will manually remove the tunnel and I don't want the operator to recreated it.

3. Remove the tunnel associated with the loadbalancer

```
kubectl delete tunnels nginx-1-tunnel
```

4. Get the service an check the external ip is still there.

```
kubectl get services
NAME             TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                  AGE
nginx-1          LoadBalancer   10.43.62.113   167.99.94.58   80:31447/TCP             25h
...
```

The service still have the node-exit IP associated in the external ip section

## Context
This is somehow an edge case. But I think one is worth fixing given the inconsistent state the loadbalancer has after the tunnel is removed

### PR DESCRIPTION
**Pull request by blackjid**
When the tunnel is deleted the tunnel external ip is removed from the loadbalancer

fixes #11 

- [x] I have raised an issue to propose this change.

## Steps to Reproduce 
1. Create a new loadblancer service
```	
kubectl run nginx-1 --image=nginx --port=80 --restart=Always
kubectl expose deployment nginx-1 --port=80 --type=LoadBalancer
```

This will make the inlets operator to create a new tunnel and update the service with the exit node ip.

2. Annotate de loadbalaner with `dev.inlets.manage=false`

This is where I think this is an edge case. This is because I will manually remove the tunnel and I don't want the operator to recreated it.

3. Remove the tunnel associated with the loadbalancer

```
kubectl delete tunnels nginx-1-tunnel
```

4. Get the service an check the external ip is still there.

```
kubectl get services
NAME             TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                  AGE
nginx-1          LoadBalancer   10.43.62.113   <pending>   80:31447/TCP             25h
...
```

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

File: controller.go [hunk 1]
```diff
@@ -598,7 +603,11 @@ func (c *Controller) updateService(tunnel *inletsv1alpha1.Tunnel, ip string) err
 	// copy.Status.LoadBalancer.Ingress = []corev1.LoadBalancerIngress{
 	// 	corev1.LoadBalancerIngress{IP: ip},
 	// }
-	copy.Spec.ExternalIPs = []string{ip}
+	if ip == "" {
```
Comment (alexellis) [inline controller.go]: I guess that we should only remove the one we added, since you can have > 1 IP, especially if you use k3s which has a "servicelb" that allocates ports on the hosts in the cluster.

Comment (blackjid) [reply controller.go]: Yes I totally agree.. 

I'm not really sure what is happening here, but at first, I implemented a way to remove just the ip from `tunnel.host.ip`. It worked, but then I realized that to add the ip the code it's also "overwriting" all the ips. 

In my tests with k3s and metallb it works fine. I have a service with ips from traefik and metallb and those ips are not being removed.

Unless there is something that is maintaining the state of the ips from  trefik and metallb.

Anyway makes sense to change the code to remove only the IP from the tunnel.

**Comment by blackjid** [comment]
Now it should be working. 
- I updated to commit also to be more insightful.
- I also improved the way the external ip is set when a new tunnel is created in order to honor any existing external ips for that service.
